---
name: Enlarge version
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - run: git config --global user.email "o.debretseni@tenantcloud.com"
      - run: git config --global user.name "Oleh Debretseni"
        with:
          fetch-depth: '0'
      - name: Enlarge version and push tag
        uses: tenantcloud/tagger@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
