---
name: Enlarge version
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: '0'
      - name: Enlarge version and push tag
        uses: tenantcloud/tagger@main
        run: |
          git config --global user.email "team@tenantcloud.com"
          git config --global user.name "tenantcloudteam"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
