---
name: Enlarge version
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: odebretseni/gha-git-credentials@v2.1
        with:
          fetch-depth: '0'
          global: true
          name: 'Oleh Debretseni'
          email: 'o.debretseni@tenantcloud.com'
          actor: 'odebretseni'
          token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Enlarge version and push tag
        uses: tenantcloud/tagger@main
